### ISSUE TITLE
Correção Exercício `0.6.1`

### ISSUE THREAD

**Issue by mathiasgheno** [adaopreuss/Exercicio0.6.1#1]
# Correção Exercício `0.6.1`

> Faça uma tabela que representa os principais influenciadores que você acompanha. Essa tabela deve conter pelo menos três influenciadores e o acesso de pelo menos duas redes sociais deles. Dentro da célula da rede social deve conter um link para a rede social do influenciador. Você deve utilizar o nth-child para definir o cor do cabeçalho e para adicionar um background nas linhas que são ímpar. Além disso, você deve fazer uso do :hover para aplicar um background diferente para o tr. Por fim, você deve aplicar um estilo único para o link baseado nas cores que são utilizadas na rede social escolhida. Veja a [imagem](https://i.imgur.com/1eLEa5N.png) como inspiração. Você tem liberdade para aplicar mais estilos e diferentes cores. 

O principal erro do seu código está no seu HTML e é um ítem básico: o link do seu HTML com o CSS. Você deve fazer isso com o uso da tag `link` dentro do seu `head`. Suponho que você faz o trabalho pelo codepen e fez o export dele através do `.zip`. Nas próximas entregas faça o envio apenas dos arquivos. 

**Nota:** 9

# Comentários

```css
  .twitter{
    background-color: #1A8CD8;
    color: white;
    padding: 8px;
    border-radius: 15px;
    text-decoration: none;
  }
  .youtube{
    background-color: #CC0000;
    color: white;
    padding: 8px;
    border-radius: 15px;
    text-decoration: none;
  }
  .instagram{
    background-color:  #EA0C5F;
    color: white;
    padding: 8px;
    border-radius: 15px;
    text-decoration: none;
  }
.facebook{
    background-color: #043d61;
    color: white;
    padding: 8px;
    border-radius: 15px;
    text-decoration: none;
    transform: scale (1.1)
}
```

Existem bastante estilos duplicados entre o `.youtube`, `.facebook`, e `.twitter`. Você deveria considerar criar uma classe derivada para agrupar esses valores duplicados. 

[^1]: [Snake Case VS Camel Case VS Pascal Case VS Kebab Case – What's the Difference Between Casings?](https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/)
